from tkinter import *
import math
root = Tk()
root.title("Simple Calculator")
root.wm_iconbitmap(r"F:\Downloads\Python apps\icon.ico")
root.configure(bg="cyan")
x = ['1','2','3','4']
root.geometry("644x276")
scvalue = StringVar()
textarea = Entry(root,textvar=scvalue,font="lucida 32 bold",bg="light blue")
scvalue.set("")
textarea.pack(fill=X)
def click(event):
    global scvalue
    text = event.widget.cget('text')
    # scvalue.set("")
    if text=="=" and text!="^":    
        try:
            value = eval(scvalue.get())
            scvalue.set(value)
        except Exception as e:
            value = "Error!"
            scvalue.set(value)
    elif text=="C":
        scvalue.set("")
    elif text=="^":
        g = math.isqrt(int(scvalue.get()))
        scvalue.set(g)
    elif text=="x":
        # text.replace("x","*")
        scvalue.set(scvalue.get().replace("x","*"))
        scvalue.set(scvalue.get() + text)
    elif text=="cos":
        g1 = math.cos(int(scvalue.get()))
        scvalue.set(g1)
    elif text=="modf":
        g2 = math.modf(int(scvalue.get()))
        scvalue.set(g2)
    elif text=="log":
        g3 = math.log(int(scvalue.get()))
        scvalue.set(g3)
    elif text=="sin":
        g4 = math.sin(int(scvalue.get()))
        scvalue.set(g4)
    elif text=="tan":
        g5 = math.tan(int(scvalue.get()))
        scvalue.set(g5)
    else:
        scvalue.set(scvalue.get() + text)
f = Frame(root,bg="white")
b = Button(f,text="9",bg='orange',pady=10)
b.pack(side=LEFT,ipadx=50)
b.bind("<Button-1>",click)
b = Button(f,text="8",bg='orange',pady=10)
b.pack(side=LEFT,ipadx=50)
b.bind("<Button-1>",click)
b = Button(f,text="7",bg='orange',pady=10)
b.pack(side=LEFT,ipadx=50)
b.bind("<Button-1>",click)
f.pack()
f = Frame(root,bg="white")
b = Button(f,text="6",bg='orange',pady=10)
b.pack(side=LEFT,ipadx=50)
b.bind("<Button-1>",click)
b = Button(f,text="5",bg='orange',pady=10)
b.pack(side=LEFT,ipadx=50)
b.bind("<Button-1>",click)
b = Button(f,text="4",bg='orange',pady=10)
b.pack(side=LEFT,ipadx=50)
b.bind("<Button-1>",click)
f.pack(padx=100)
f = Frame(root,bg="white")
b = Button(f,text="3",bg='orange',pady=10)
b.pack(side=LEFT,ipadx=50)
b.bind("<Button-1>",click)
b = Button(f,text="2",bg='orange',pady=10)
b.pack(side=LEFT,ipadx=50)
b.bind("<Button-1>",click)
b = Button(f,text="1",bg='orange',pady=10)
b.pack(side=LEFT,ipadx=50)
b.bind("<Button-1>",click)
f.pack(padx=100)
f = Frame(root,bg="white")
b = Button(f,text="C",bg='orange',pady=10)
b.pack(side=LEFT,ipadx=50)
b.bind("<Button-1>",click)
b = Button(f,text="0",bg='orange',pady=10)
b.pack(side=LEFT,ipadx=50)
b.bind("<Button-1>",click)
b = Button(f,text="=",bg='orange',pady=10)
b.pack(side=LEFT,ipadx=50)
b.bind("<Button-1>",click)
f.pack(padx=100)
f1 = Frame(root, bg='white')
b = Button(f1,text="+",bg='orange',pady=10)
b.pack(ipadx=50)
b.bind("<Button-1>",click)
b = Button(f1,text="-",bg='orange',pady=10)
b.pack(ipadx=50)
b.bind("<Button-1>",click)
b = Button(f1,text="*",bg='orange',pady=10)
b.pack(ipadx=50)
b.bind("<Button-1>",click)
b = Button(f1,text="/",bg='orange',pady=10)
b.pack(ipadx=50)
b.bind("<Button-1>",click)
f1.place(x = 30, y = 55)

f2 = Frame(root, bg="white")
b = Button(f2,text="^",bg='orange',pady=10)
b.pack(ipadx=50)
b.bind("<Button-1>",click)
b = Button(f2,text="+-",bg='orange',pady=10)
b.pack(ipadx=50)
b.bind("<Button-1>",click)
b = Button(f2,text="%",bg='orange',pady=10)
b.pack(ipadx=50)
b.bind("<Button-1>",click)
b = Button(f2,text=".",bg='orange',pady=10)
b.pack(ipadx=50)
b.bind("<Button-1>",click)
f2.place(x = 500, y = 55)

f3 = Frame(root, bg="white")
b = Button(f3,text="cos",bg='orange',pady=10)
b.pack(ipadx=44, side=LEFT)
b.bind("<Button-1>",click)
b = Button(f3,text="modf",bg='orange',pady=10)
b.pack(ipadx=44, side=LEFT)

b.bind("<Button-1>",click)
b = Button(f3,text="log",bg='orange',pady=10)
b.pack(ipadx=44, side=LEFT)
b.bind("<Button-1>",click)
b = Button(f3,text="sin",bg='orange',pady=10)
b.pack(ipadx=44, side=LEFT)
b.bind("<Button-1>",click)
b = Button(f3,text="tan",bg='orange',pady=10)
b.pack(ipadx=44, side=LEFT)
b.bind("<Button-1>",click)
f3.place(x = 30,y = 230)
root.mainloop()