from tkinter import *
x="*"
# from tkinter.ttk import *
# style=Style()
# style.configure("TButton",font=("calibri",10,'bold'),foreground='red')
def click(event):
    global scvalue
    text = event.widget.cget("text")
    # print(text)
    if text=="=":
        if scvalue.get().isdigit():
            value=int(scvalue.get())
        else:
            try:
                value=eval(scvalue.get())
            
            except Exception as e:
                value="Error!!"
                screen.update()
        scvalue.set(value)
        screen.update()
    elif text=="C":
        scvalue.set("")
        screen.update()

    else:
        scvalue.set(scvalue.get() + text)
        screen.update()
root=Tk()
root.geometry("644x640")
root.title("Calculator")
scvalue=StringVar()
scvalue.set("")
screen=Entry(root,textvar=scvalue,font="comicsansms 40 bold")
screen.pack(fill=X,padx=10,pady=10)
f=Frame(root,bg="red")
b=Button(f,text="9",padx=7,pady=7,font="comicsansms 35 bold")
b.pack(side=LEFT,ipadx=10,padx=9,pady=9)
b.bind("<Button-1>",click)
b=Button(f,text="8",padx=7,pady=7,font="comicsansms 35 bold")
b.pack(side=LEFT,padx=9,pady=9)
b.bind("<Button-1>",click)
b=Button(f,text="7",padx=7,pady=7,font="comicsansms 35 bold")
b.pack(side=LEFT,padx=9,pady=9)
b.bind("<Button-1>",click)
b=Button(f,text="6",padx=7,pady=7,font="comicsansms 35 bold")
b.pack(side=LEFT,padx=9,pady=9)
b.bind("<Button-1>",click)
f.pack()

f=Frame(root,bg="red")
b=Button(f,text="5",padx=7,pady=7,font="comicsansms 35 bold")
b.pack(side=LEFT,ipadx=10,padx=9,pady=9)
b.bind("<Button-1>",click)
b=Button(f,text="4",padx=7,pady=7,font="comicsansms 35 bold")
b.pack(side=LEFT,padx=9,pady=9)
b.bind("<Button-1>",click)
b=Button(f,text="3",padx=7,pady=7,font="comicsansms 35 bold")
b.pack(side=LEFT,padx=9,pady=9)
b.bind("<Button-1>",click)
b=Button(f,text="2",padx=7,pady=7,font="comicsansms 35 bold")
b.pack(side=LEFT,padx=9,pady=9)
b.bind("<Button-1>",click)
f.pack()
f=Frame(root,bg="red")
b=Button(f,text="1",padx=7,pady=7,font="comicsansms 35 bold")
b.pack(side=LEFT,ipadx=10,padx=9,pady=9)
b.bind("<Button-1>",click)
b=Button(f,text="0",padx=7,pady=7,font="comicsansms 35 bold")
b.pack(side=LEFT,padx=9,pady=9)
b.bind("<Button-1>",click)
b=Button(f,text="+",padx=7,pady=7,font="comicsansms 35 bold")
b.pack(side=LEFT,padx=9,pady=9)
b.bind("<Button-1>",click)
b=Button(f,text="-",padx=7,pady=7,font="comicsansms 35 bold")
b.pack(side=LEFT,padx=9,pady=9)
b.bind("<Button-1>",click)
f.pack()
f=Frame(root,bg="red")
b=Button(f,text=x,padx=7,pady=7,font="comicsansms 35 bold")
b.pack(side=LEFT,ipadx=9,padx=9,pady=9)
b.bind("<Button-1>",click)
b=Button(f,text="/",padx=7,pady=7,font="comicsansms 35 bold")
b.pack(side=LEFT,padx=9,pady=9)
b.bind("<Button-1>",click)
b=Button(f,text=".",padx=7,pady=7,font="comicsansms 35 bold")
b.pack(side=LEFT,padx=9,pady=9)
b.bind("<Button-1>",click)
f.pack()
f=Frame(root,bg="red")
b=Button(f,text="=",padx=7,pady=7,font="comicsansms 35 bold")
b.pack(side=RIGHT,padx=9,pady=9)
b.bind("<Button-1>",click)
b=Button(f,text="C",padx=7,pady=7,font="comicsansms 35 bold")
b.pack(side=LEFT,padx=9,pady=9)
b.bind("<Button-1>",click)
f.pack()
root.mainloop()
