# Generated by Django 4.1.9 on 2023-06-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro', models.TextField()),
                ('role', models.CharField(max_length=10)),
                ('response', models.TextField()),
            ],
        ),
    ]
