l = []
print("Tell me your seven favourite fruits:\n")
x1 = input("Enter Fruit no 1:\t")
x2 = input("Enter Fruit no 2:\t")
x3 = input("Enter Fruit no 3:\t")
x4 = input("Enter Fruit no 4:\t")
x5 = input("Enter Fruit no 5:\t")
x6 = input("Enter Fruit no 6:\t")
x7 = input("Enter Fruit no 7:\t")
l.append(x1)
l.append(x2)
l.append(x3)
l.append(x4)
l.append(x5)
l.append(x6)
l.append(x7)
print("Your favourite fruits are:",l)