from tkinter import *
root = Tk()
root.title("Naman Login")
Label(root,text="Welcome to Naman login\n",font="comicsansms 20 bold",pady=15).grid(row=0,column=2)
N = Label(root,text="Name:\n",font="comicsansms 10 bold").grid(row=5,column=2)
ids = Label(root,text="gmail id:\n",font="comicsansms 10 bold").grid(row=6,column=2)
passpo = Label(root,text="password:\n",font="comicsansms 10 bold").grid(row=7,column=2)
name=StringVar()
password=StringVar()
checkv=IntVar()
def info():
    with open("login info.txt","rt") as f:
        h=f.read()
        print(h)
def login():
    lo=Label(root,text="signing in.....\n" ,font="comicsansms 20").grid(row=15,column=3)
    naa=Label(root,text=f"id:{idv.get()}\n,password:{passv.get()}\n,name:{nv.get()}\n",font="comicsansms 20 bold").grid(row=20,column=2)
    l=Label(root,text="login was sucessfull!!!!\n" ,font="comicsansms 20").grid(row=20,column=3)
    with open("login info.txt","w") as h:
        h.write(f"name:{namep.get()}, password:{passp.get()}, id:{youridp.get()}")
nv=StringVar()
idv=StringVar()
passv=StringVar()
namep=Entry(textvariable=nv)
passp=Entry(textvariable=passv)
youridp=Entry(textvariable=idv)
namep.grid(row=5 ,column=3)
passp.grid(row=7,column=3)
youridp.grid(row=6,column=3)
btn1=Button(root,text="login!!!",command=login)
btn1.grid(row=10, column=2)
btn2=Button(root,text="my info",command=info)
btn2.grid(row=15,column=2)
check=Checkbutton(text="Want to login???",variable=checkv)
check.grid(row=9,column=2)
root.geometry("644x544")
mainloop() 