from tkinter import *
import numpy as np
class GUI(Tk):
    def __init__(self):
        super().__init__()
    def screen(self):
        self.scvalue = StringVar(self)
        self.scr = Entry(self, textvar = self.scvalue, font="lucida 30 bold", bg = "sky blue", fg = "black")
        self.scr.pack()
    def click(self, event):
        self.text = event.widget.cget('text')
        try:
            if self.text=='=':
                try:
                    self.value = eval(self.scvalue.get())
                    self.scvalue.set(self.value)
                except Exception as e:
                    # print(e)
                    self.scvalue.set("Error!") 
            elif self.text=='C':
                self.scvalue.set("")
            elif self.text == '√':
                self.scvalue.set(np.sqrt(int(self.scvalue.get())))
            elif self.text == 'cos':
                self.scvalue.set(np.cos(int(self.scvalue.get())))
            elif self.text == 'In':
                self.scvalue.set(np.log(int(self.scvalue.get())))
            elif self.text == 'log':
                self.scvalue.set(np.log10(int(self.scvalue.get())))
            elif self.text == 'modf':
                self.scvalue.set(np.modf(int(self.scvalue.get())))
            elif self.text == 'tan':
                self.scvalue.set(np.tan(int(self.scvalue.get())))
            elif self.text == 'mod':
                self.scvalue.set(np.mod(int(self.scvalue.get())))
            elif self.text == 'sin':
                self.scvalue.set(np.sin(int(self.scvalue.get())))
            elif self.text == 'Int':
                # print(self.scvalue.get())
                self.a = float(str(self.scvalue.get()))
                self.a = int(self.a)
                self.scvalue.set(str(self.a))
            elif self.text == 'n!':
                self.scvalue.set(np.math.factorial(int(self.scvalue.get())))
            elif self.text == "<--":
                # a = int(len(self.scr.get()))
                self.scr.delete(int(len(self.scr.get()))-1)
                # self.scr.delete(1)
            else:
                self.scvalue.set(self.scvalue.get() + self.text)
                self.scr.update()
        except Exception as e:
            print(e)
            self.scvalue.set("Error!")
    def bt(self):
        self.f = Frame(self, bg = "white")
        self.b = Button(self.f, text = "9", padx=10, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.b = Button(self.f, text = "8", padx=10, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.b = Button(self.f, text = "7", padx=10, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.f.pack()
        self.f = Frame(self, bg = "white")
        self.b = Button(self.f, text = "6", padx=10, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.b = Button(self.f, text = "5", padx=10, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.b = Button(self.f, text = "4", padx=10, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.f.pack()
        self.f = Frame(self, bg = "white")
        self.b = Button(self.f, text = "3", padx=10, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.b = Button(self.f, text = "2", padx=10, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.b = Button(self.f, text = "1", padx=10, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.f.pack()
        self.f = Frame(self, bg = "white")
        self.b = Button(self.f, text = "0", padx=10, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.b = Button(self.f, text = "sin", padx=10, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.b = Button(self.f, text = "Int", padx=10, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.f.pack()
        self.f = Frame(self, bg = "white")
        self.b = Button(self.f, text = "+", padx=10, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.b = Button(self.f, text = "-", padx=10, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.b = Button(self.f, text = "*", padx=10, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.f.pack()
        self.f = Frame(self, bg = "white")
        self.b = Button(self.f, text = "/", padx=10, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.b = Button(self.f, text = "%", padx=10, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.b = Button(self.f, text = "log", padx=10, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.f.pack()
        self.f = Frame(self, bg = "white")
        self.b = Button(self.f, text = "√", padx=10, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.b = Button(self.f, text = "C", padx=10, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.b = Button(self.f, text = ".", padx=10, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.f.pack()
        self.f = Frame(self, bg = "white")
        self.b = Button(self.f, text = "cos", padx=7, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.b = Button(self.f, text = "modf", padx=7, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.b = Button(self.f, text = "tan", padx=7, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.f.pack()
        self.f = Frame(self, bg = "white")
        self.b = Button(self.f, text = "In", padx=7, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.b = Button(self.f, text = "n!", padx=7, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.f.pack()
        self.b.configure(bg = "orange")
        self.b = Button(self.f, text = "<--", padx=7, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.f.pack()
        self.b.configure(bg = "orange")
        self.f.pack()
        self.f = Frame(self, bg = "white")
        self.b = Button(self.f, text = "(", padx=7, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.b = Button(self.f, text = "=", padx=7, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.b = Button(self.f, text = ")", padx=7, pady=5)
        self.b.pack(ipadx=50, side = LEFT)
        self.b.bind('<Button-1>', self.click)
        self.b.configure(bg = "orange")
        self.f.pack()
        self.b.configure(bg = "orange")

root = GUI()

root.geometry("444x397")
root.screen()
root.title("OOPS Calculator")
root.bt()
root.configure(bg = "sky blue")
root.mainloop()
